# name the workflow
name: 'thhart deploy to dev workflow'

# ensure only 1 job runs at the same time
concurrency: 1

# trigger whenever there is a push to main branch
on:
  push:
    branches:
      - main

jobs:
  # Used by the "pipeline_update" job to deploy the bundle.
  # Bundle validation is automatically performed as part of this deployment.
  # If validation fails, this workflow fails.
  deploy:
    name: 'thhart deploy to dev job'
    runs-on: ubuntu-latest

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "dev" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DBX_COMMUNITY }}
          DATABRICKS_BUNDLE_ENV: thhart_target_dev